### PR TITLE
Add shops function

### PR DESCRIPTION
**Pull request by Sergix**
Added add function to /shops

Work from this branch in developing shop limits and other add-command related pushes.

### TODO:
- [ ] Fix tp to deleted shop
- [x] /shops tp
- [x] /shops add
- [x] /shops create

### CODE REVIEW

**Comment by NCSGeek** [comment]
Added the fully integrated shop limit system. There are comments in the code if you wanted to look. (Hashtags are comments in Skript)

Skript wont let me send files, so here: http://www.mediafire.com/file/t11e7vgb0rcytb6/thanks_github_for_not_supporting_.sk_as_a_file_type.zip

**Comment by Sergix** [comment]
Lol for it not supporting it XD; I'll check it in the morning, apparently GitHub sends me email notifications whenever I get a reply.

**Comment by Sergix** [comment]
Pushed the changes in the latest commit: https://github.com/Sergix7440/Skript-Server/pull/2/commits/c30903671214e1021982d07bc3a1553eda32b959

As for the issue regarding being able to teleport after the shop is deleted, from your code everything looks fine; in fact, based on your code it's almost as if the player is teleporting to an undefined value if it is removed. Must be a plugin issue, I would just contact the dev.

Everything looks good so far!

**Comment by Sergix** [comment]
By the way, instead of posting your files in this discussion itself by commenting, push your changes to the "shopstp-add" branch. I found out that if you push your changes to that branch all of them will show up in this conversation, as shown above. Just make sure you are pushing them to the correct branch! 😉

**Comment by Sergix** [comment]
Check to see if the new file update looks good: https://github.com/Sergix7440/Skript-Server/pull/2/commits/c6933576befb5d251dc1beec9e6e774cbe450dfd

Also need you to add essentials to the plugins folder in the master branch. (again, make sure its the master branch 😛  )

**Comment by Sergix** [comment]
We ever gonna finish this? xD

**Comment by NCSGeek** [comment]
lol

**Comment by Sergix** [comment]
ey r u there right now?

**Pull request closed without merging**
